enum MESSAGE_TYPE {
  MESSAGE_TYPE_QUIT = 1,
  MESSAGE_TYPE_PING = 2,
  MESSAGE_TYPE_NICKNAME = 3,
  MESSAGE_TYPE_JOIN = 4,
  MESSAGE_TYPE_KICK = 5,
  MESSAGE_TYPE_MUTE = 6,
  MESSAGE_TYPE_UNMUTE = 7,
  MESSAGE_TYPE_HELP = 8,
  MESSAGE_TYPE_RETRANSMISSION = 9,
};

int identify_message_type(char *message);